### ISSUE TITLE
BTA crashed when right clicking the block.

### ISSUE THREAD

**Issue by jakeayy** [FatherCheese/bta-worldedit#5]
Using the latest version of Babric;
So my problem is I can't select region with WorldEdit using wand because right/shift+right clicking a block with it crashes the game. Here's the log I got on crash screen:

```
Minecraft ran into an unexpected problem that it cannot recover from!

The current game has quit, please restart the game.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 5/17/24 12:26 PM

Minecraft: Better than Adventure! 7.2 Prerelease 1
OS: Windows 10 (amd64) version 10.0
Java: 1.8.0_401, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.4
OpenGL: Intel(R) UHD Graphics version 4.6.0 - Build 30.0.100.9864, Intel

java.lang.NoSuchMethodError: net.minecraft.core.entity.player.EntityPlayer.addChatMessage(Ljava/lang/String;)V
    at net.minecraft.core.item.Item.handler$zbd000$worldedit$useItem(Item.java:1034)
    at net.minecraft.core.item.Item.onItemUse(Item.java:89)
    at net.minecraft.core.item.ItemStack.useItem(ItemStack.java:120)
    at net.minecraft.client.player.controller.PlayerController.useItemOn(PlayerController.java:260)
    at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1127)
    at net.minecraft.client.Minecraft.checkBoundInputs(Minecraft.java:1564)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1289)
    at net.minecraft.client.Minecraft.run(Minecraft.java:831)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by jakeayy** [comment]
Opened pull request fixing this issue at https://github.com/FatherCheese/bta-worldedit/pull/6
